### ISSUE TITLE
Zarovnání stránky na střed

### ISSUE THREAD

**Issue by mohlerit** [AnnaK16/PROJEKT-Vizitka#1]
Ahoj Anno,
hezká práce. Líbí se mi, že jsis s tím nějak poprala, ale to vystředění není úplně 100%. Napozicování na střed pomocí left: 35% bude hodně záležet podle displeje. Málem jsme se nechal ošálit, ale zdálo se mi to trošku mimo středovou osu. 

Pokud chceš vystředit vizitku, tak k tomu použij `margin-left: auto` a `margin-right: auto`. Musíš ale zrušit `position: absolute` a zbavit se také vlastností `left` a `top`. Aby jsi odsadila vizitku od vrchu použij `margin-top` no a aby se ti obrázek nepozicoval dle stránky ale dle vizitky je třeba nadřazenému elementu nastavit relativní pozicování. Tedy vizitce nastav `position: relative`.

Jinak jeto moc pěkná práce.

## Podmínky pro ohodnocení
- [x] Upravit zarovnání stránky na střed

**Comment by AnnaK16** [comment]
Ahoj Martine,
provedla jsem úpravy a vizitka je úplně vlevo :( Kde je chyba?

Anna

**Comment by mohlerit** [comment]
Problém je v `display: inline-block;`. Mění ti chování. Mělo by to být `display: block;` a nebo tam vůbec nemusí být, protože `div` blockový element a `display: block;` je jeho výchozí hodnota.

**Comment by AnnaK16** [comment]
Dik moc, ted uz je to snad v poradku.
Dekuji za povzbudive hodnoceni :)

**Comment by mohlerit** [comment]
Je to v pořádku. Skvělá práce. Uzavírám Issue a dávám hodnocení do classroom
